backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: author, label: Author }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { name: date, label: Date, widget: date }
      - { name: body, label: body, widget: markdown }
  - name: team_members
    label: "Team Member"
    folder: src/pages/about/_members
    create: true
    fields:
      - { name: name, label: Name }
      - { name: job, label: Job }
      - { name: image, label: Featured Image, widget: image, required: false }
      - { name: order, label: Order, widget: number, required: false }
  - name: jobs
    label: "Job"
    folder: src/pages/careers/_jobs
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: Url }
   - name: article
    label: article
    folder: src/pages/article/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: author, label: Author }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: list }
      - { name: date, label: Date, widget: date }
      - { name: body, label: body, widget: markdown }
